// @generated by tools/specgen. DO NOT EDIT.

pub const PROFILE_NAME: &str = "hybrid-vtol";
pub const CONTROL_HZ: u64 = 60;
pub const PROFILE_DEADLINE_MS: u64 = 8;
pub const CAP_VTOL: bool = true;
pub const CAP_FIXED_WING: bool = true;
