#!/usr/bin/env python3
"""Hard-fail guard for release-bound placeholder/scaffold artifacts."""

from __future__ import annotations

import argparse
from pathlib import Path

FORBIDDEN_PATTERNS = [
    "placeholder",
    "starter",
    "scaffold",
    "baseline manifest placeholder",
    "placeholder report generated by assurancepack tool",
]

RELEASE_DOMAIN_PREFIXES = [
    "conformance/",
    "evidence/",
    "governance/",
    "safety-case/",
]


def collect_files(root: Path, globs: list[str]) -> list[Path]:
    files: list[Path] = []
    for pattern in globs:
        files.extend(p for p in root.glob(pattern) if p.is_file())
    return sorted(set(files))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument(
        "--include",
        nargs="*",
        default=[
            "evidence/manifests/*.json",
            "conformance/fixtures/tasc/*.json",
            "conformance/reports/*.json",
            "policies/*.json",
        ],
    )
    args = parser.parse_args()

    root = Path(args.repo_root).resolve()
    files = collect_files(root, args.include)

    violations: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        lower = text.lower()
        for pattern in FORBIDDEN_PATTERNS:
            if pattern in lower:
                rel = path.relative_to(root)
                violations.append(f"{rel}: contains forbidden pattern '{pattern}'")

    gitkeeps = sorted(root.rglob(".gitkeep"))
    for path in gitkeeps:
        rel = path.relative_to(root).as_posix()
        if any(rel.startswith(prefix) for prefix in RELEASE_DOMAIN_PREFIXES):
            violations.append(f"{rel}: .gitkeep is not allowed in release domains")

    if violations:
        print("release guard failed:")
        for v in violations:
            print(f"- {v}")
        return 1

    print(f"release guard passed ({len(files)} files scanned)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
